-- EffectConfigConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class EffectConfig
---@field 前摇特效 string
---@field 施法特效 string
---@field 飞行特效 string
---@field 击中特效 string
---@field 目标特效 string
---@field 音效配置 table
---@field 镜头效果 table

---@class EffectConfigConfig
---@field Data table<string, EffectConfig>

---@type EffectConfigConfig
local EffectConfigConfig = {}

-- --- AUTO GENERATED CONFIG BEGIN ---
EffectConfigConfig.Data = {
    ["加速特效"] = {
        ["前摇特效"] = "",
        ["施法特效"] = "",
        ["飞行特效"] = "",
        ["击中特效"] = "",
        ["目标特效"] = "",
        ["音效配置"] = {
            ["施法音效"] = "",
            ["击中音效"] = "",
        },
        ["镜头效果"] = {
            ["震荡强度"] = 0,
            ["震荡时间"] = 0,
        },
        ["name"] = "加速特效",
        ["hideFlags"] = 0,
    },
}
-- --- AUTO GENERATED CONFIG END ---

return EffectConfigConfig
