-- ItemTypeConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class ItemType
---@field 名字 string
---@field 物品类型 number
---@field 描述 string
---@field 图标 string
---@field 品级 number
---@field 战力 number
---@field 强化倍率 number
---@field 强化材料增加倍率 number
---@field 最大强化等级 number
---@field 图鉴完成奖励数量 number
---@field 图鉴高级完成奖励数量 number
---@field 售出价格 number
---@field 在背包里显示 boolean
---@field 货币序号 number
---@field 获得音效 string
---@field 取消获得物品 boolean
---@field 获得执行指令 string[]
---@field 使用执行指令 string[]
---@field 分解可得 table[]

---@class ItemTypeConfig
---@field Data table<string, ItemType>

---@type ItemTypeConfig
local ItemTypeConfig = {}

-- --- AUTO GENERATED CONFIG BEGIN ---
ItemTypeConfig.Data = {
    ["加速卡"] = {
        ["名字"] = "加速卡",
        ["物品类型"] = 1,
        ["描述"] = "",
        ["图标"] = "",
        ["品级"] = 0,
        ["战力"] = 0,
        ["强化倍率"] = 0,
        ["强化材料增加倍率"] = 0,
        ["最大强化等级"] = 0,
        ["图鉴完成奖励数量"] = 0,
        ["图鉴高级完成奖励数量"] = 0,
        ["售出价格"] = 0,
        ["在背包里显示"] = true,
        ["货币序号"] = 0,
        ["获得音效"] = "",
        ["取消获得物品"] = false,
        ["获得执行指令"] = {
        },
        ["使用执行指令"] = {
        },
        ["分解可得"] = {
            {
                ["物品"] = nil,
                ["数量"] = 0,
            },
        },
        ["name"] = "加速卡",
        ["hideFlags"] = 0,
    },
}
-- --- AUTO GENERATED CONFIG END ---

return ItemTypeConfig
