-- PetConfig.lua
-- Generated by ConfigExporter. Any custom code will be overwritten.

---@class PetBaseStats
---@field 生命值 number
---@field 攻击力 number
---@field 防御力 number
---@field 敏捷 number
---@field 智力 number

---@class PetGrowthRate
---@field 生命值成长 string
---@field 攻击力成长 string
---@field 防御力成长 string
---@field 敏捷成长 string
---@field 智力成长 string

---@class PetLevelEffect
---@field level number
---@field 解锁技能 string
---@field 属性加成 table<string, number>
---@field 特殊效果 string

---@class PetStarEffect
---@field star number
---@field 属性倍率 table<string, number>
---@field 新增技能 string
---@field 特殊能力 string
---@field 升星材料 table<string, number>

---@class PetStarCost
---@field star number
---@field 消耗物品 table<string, number>
---@field 成功率 number

---@class PetCarryEffect
---@field star number
---@field 效果名称 string
---@field 效果描述 string
---@field 效果数值 string
---@field 触发条件 string
---@field 作用范围 string

---@class PetEvolution
---@field 需要等级 number
---@field 需要材料 table<string, number>

---@class Pet
---@field 宠物名称 string
---@field 宠物描述 string
---@field 宠物类型 string
---@field 稀有度 string
---@field 初始等级 number
---@field 最大等级 number
---@field 元素类型 string
---@field 基础属性 PetBaseStats
---@field 成长率 PetGrowthRate
---@field 等级效果 PetLevelEffect[]
---@field 升星效果 PetStarEffect[]
---@field 升星消耗 PetStarCost[]
---@field 携带效果 PetCarryEffect[]
---@field 技能列表 string[]
---@field 进化条件 PetEvolution
---@field 进化后形态 string
---@field 获取方式 string[]
---@field 模型资源 string
---@field 头像资源 string
---@field 音效资源 string
---@field 特殊标签 string[]

---@class PetConfig
---@field Data table<string, Pet>

---@type PetConfig
local PetConfig = {}

-- --- AUTO GENERATED CONFIG BEGIN ---
PetConfig.Data = {
}
-- --- AUTO GENERATED CONFIG END ---

return PetConfig 